ALTER TABLE user_info ADD COLUMN first_name VARCHAR(255) NOT NULL;
ALTER TABLE user_info ADD COLUMN last_name VARCHAR(255) NOT NULL;
ALTER TABLE user_info ADD COLUMN admin BOOLEAN NOT NULL DEFAULT FALSE;